# Generated by Django 6.0 on 2026-01-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_options_alter_products_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id'], 'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
